/**
 * Push Boonyang Database Schema to Supabase
 * Direct deployment via Supabase REST API
 */

const SUPABASE_URL = 'https://cbxicbynxnprscwqnyld.supabase.co';
const SUPABASE_SERVICE_ROLE_KEY = 'YOUR_SERVICE_ROLE_KEY_HERE'; // Get from Supabase Dashboard > Settings > API

const SQL_SCHEMA = `
-- Enable required extension
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- ============================================
-- Table: botdata
-- ============================================
CREATE TABLE IF NOT EXISTS botdata (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_code TEXT,
  field_unknown TEXT,
  item_name TEXT,
  lot_number TEXT,
  on_hand_quantity INTEGER DEFAULT 0,
  alternative_key_1 TEXT,
  alternative_key_2 TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_botdata_item_code ON botdata(item_code);
CREATE INDEX IF NOT EXISTS idx_botdata_item_name ON botdata(item_name);
CREATE INDEX IF NOT EXISTS idx_botdata_alt_key_1 ON botdata(alternative_key_1);
CREATE INDEX IF NOT EXISTS idx_botdata_alt_key_2 ON botdata(alternative_key_2);

-- ============================================
-- Table: inventdata
-- ============================================
CREATE TABLE IF NOT EXISTS inventdata (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_name TEXT,
  stock_quantity INTEGER DEFAULT 0,
  stock_status TEXT GENERATED ALWAYS AS (
    CASE
      WHEN stock_quantity >= 4 THEN 'มีสินค้า'
      ELSE 'ติดต่อแอดมิน'
    END
  ) STORED,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_inventdata_item_name ON inventdata(item_name);
CREATE INDEX IF NOT EXISTS idx_inventdata_stock_status ON inventdata(stock_status);
CREATE INDEX IF NOT EXISTS idx_inventdata_item_name_trgm ON inventdata USING GIN (item_name gin_trgm_ops);

-- ============================================
-- Table: userdata
-- ============================================
CREATE TABLE IF NOT EXISTS userdata (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT,
  display_name TEXT,
  picture_url TEXT,
  status_message TEXT,
  image_formula TEXT,
  registration_date DATE,
  registration_time TIME(0),
  language TEXT,
  group_name TEXT,
  group_id TEXT,
  status_register TEXT,
  reference TEXT,
  name TEXT,
  surname TEXT,
  shop_name TEXT,
  tax_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  last_interaction_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_userdata_user_id ON userdata(user_id);
CREATE INDEX IF NOT EXISTS idx_userdata_status_register ON userdata(status_register);
CREATE INDEX IF NOT EXISTS idx_userdata_shop_name ON userdata(shop_name);
CREATE INDEX IF NOT EXISTS idx_userdata_last_interaction ON userdata(last_interaction_at DESC);

-- ============================================
-- Table: system_settings
-- ============================================
CREATE TABLE IF NOT EXISTS system_settings (
  id SERIAL PRIMARY KEY,
  bot_enabled BOOLEAN DEFAULT true,
  stock_enabled BOOLEAN DEFAULT true,
  stock_require_approval BOOLEAN DEFAULT true,
  register_required BOOLEAN DEFAULT true,
  line_channel_token TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO system_settings (bot_enabled, stock_enabled, stock_require_approval, register_required)
VALUES (true, true, true, true)
ON CONFLICT DO NOTHING;

-- ============================================
-- Table: reply_templates
-- ============================================
CREATE TABLE IF NOT EXISTS reply_templates (
  id SERIAL PRIMARY KEY,
  keyword TEXT NOT NULL UNIQUE,
  reply_type TEXT NOT NULL,
  reply_content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- Enable RLS
-- ============================================
ALTER TABLE botdata ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventdata ENABLE ROW LEVEL SECURITY;
ALTER TABLE userdata ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE reply_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role: Full access to botdata"
  ON botdata FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Service role: Full access to inventdata"
  ON inventdata FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Service role: Full access to userdata"
  ON userdata FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Service role: Full access to system_settings"
  ON system_settings FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Service role: Full access to reply_templates"
  ON reply_templates FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Public read access on botdata"
  ON botdata FOR SELECT TO anon USING (true);

CREATE POLICY "Public read access on inventdata"
  ON inventdata FOR SELECT TO anon USING (true);

CREATE POLICY "Public read access on reply_templates"
  ON reply_templates FOR SELECT TO anon USING (true);

-- ============================================
-- Functions & Triggers
-- ============================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_botdata_updated_at ON botdata;
CREATE TRIGGER update_botdata_updated_at
  BEFORE UPDATE ON botdata
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_inventdata_updated_at ON inventdata;
CREATE TRIGGER update_inventdata_updated_at
  BEFORE UPDATE ON inventdata
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_userdata_updated_at ON userdata;
CREATE TRIGGER update_userdata_updated_at
  BEFORE UPDATE ON userdata
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_system_settings_updated_at ON system_settings;
CREATE TRIGGER update_system_settings_updated_at
  BEFORE UPDATE ON system_settings
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_reply_templates_updated_at ON reply_templates;
CREATE TRIGGER update_reply_templates_updated_at
  BEFORE UPDATE ON reply_templates
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Completed
SELECT '✅ Database schema created successfully!' as status;
`;

/**
 * Execute SQL via Supabase REST API
 */
async function executeSQL(sql: string) {
  const response = await fetch(`${SUPABASE_URL}/rest/v1/rpc/execute`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'apikey': SUPABASE_SERVICE_ROLE_KEY,
      'Authorization': `Bearer ${SUPABASE_SERVICE_ROLE_KEY}`,
      'Prefer': 'return=representation'
    },
    body: JSON.stringify({
      sql: sql
    })
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Failed to execute SQL: ${error}`);
  }

  const result = await response.json();
  return result;
}

/**
 * Push schema to Supabase
 */
async function pushSchema() {
  console.log('🚀 Pushing Boonyang Inventory database schema to Supabase...');
  console.log('📍 Target: ' + SUPABASE_URL);

  try {
    // Split SQL into individual statements
    const statements = SQL_SCHEMA
      .split(';')
      .map(s => s.trim())
      .filter(s => s.length > 0 && !s.startsWith('--'));

    console.log(`📝 Total statements: ${statements.length}`);

    let successCount = 0;
    let errorCount = 0;

    // Execute each statement
    for (let i = 0; i < statements.length; i++) {
      const statement = statements[i];

      // Skip empty lines or comments
      if (!statement || statement.startsWith('--')) {
        continue;
      }

      try {
        console.log(`\n[${i + 1}/${statements.length}] Executing...`);
        console.log(`📄 Statement:\n${statement.substring(0, 100)}...`);

        const result = await executeSQL(statement);
        successCount++;

        if (result.data && result.data.length > 0) {
          console.log(`✅ Result:`, result.data);
        } else {
          console.log(`✅ Success`);
        }
      } catch (error: {
        errorCount++;
        console.error(`❌ Error:`, error.message);

        // Continue with other statements even if one fails
      });
    }

    console.log('\n' + '='.repeat(50));
    console.log(`📊 Summary:`);
    console.log(`  ✅ Success: ${successCount} statements`);
    console.log(`  ❌ Errors: ${errorCount} statements`);
    console.log(`  📝 Total: ${statements.length} statements`);
    console.log('='.repeat(50));

    if (successCount > 0) {
      console.log('\n✅ Database schema created successfully!');
      console.log('\n📋 Tables created:');
      console.log('  • botdata');
      console.log('  • inventdata');
      console.log('  • userdata');
      console.log('  • system_settings');
      console.log('  • reply_templates');
      console.log('\n🔗 View at: https://cbxicbynxnprscwqnyld.supabase.co/table-editor');
    } else if (errorCount === 0) {
      console.log('\n✅ Database schema already exists or no changes needed!');
    }
  } catch (error) {
    console.error('\n❌ Fatal error:', error);
    process.exit(1);
  }
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  pushSchema();
}

export { pushSchema };
