-- Create botdata_history table
CREATE TABLE IF NOT EXISTS botdata_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  original_id BIGINT,
  item_code TEXT,
  field_unknown TEXT,
  item_name TEXT,
  lot_number TEXT,
  on_hand_quantity INTEGER,
  alternative_key_1 TEXT,
  alternative_key_2 TEXT,
  backed_up_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for botdata_history
CREATE INDEX IF NOT EXISTS idx_botdata_history_original_id ON botdata_history(original_id);
CREATE INDEX IF NOT EXISTS idx_botdata_history_item_code ON botdata_history(item_code);
CREATE INDEX IF NOT EXISTS idx_botdata_history_backed_up_at ON botdata_history(backed_up_at DESC);

-- Create inventdata_history table
CREATE TABLE IF NOT EXISTS inventdata_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  original_id BIGINT,
  item_name TEXT,
  stock_quantity INTEGER,
  backed_up_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for inventdata_history
CREATE INDEX IF NOT EXISTS idx_inventdata_history_original_id ON inventdata_history(original_id);
CREATE INDEX IF NOT EXISTS idx_inventdata_history_item_name ON inventdata_history(item_name);
CREATE INDEX IF NOT EXISTS idx_inventdata_history_backed_up_at ON inventdata_history(backed_up_at DESC);

-- Enable RLS
ALTER TABLE botdata_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventdata_history ENABLE ROW LEVEL SECURITY;

-- Drop policies if exist
DROP POLICY IF EXISTS "Service role: Full access to botdata_history" ON botdata_history;
DROP POLICY IF EXISTS "Service role: Full access to inventdata_history" ON inventdata_history;
DROP POLICY IF EXISTS "Public read access on botdata_history" ON botdata_history;
DROP POLICY IF EXISTS "Public read access on inventdata_history" ON inventdata_history;

-- Create policies
CREATE POLICY "Service role: Full access to botdata_history"
  ON botdata_history FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Service role: Full access to inventdata_history"
  ON inventdata_history FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Public read access on botdata_history"
  ON botdata_history FOR SELECT TO anon USING (true);

CREATE POLICY "Public read access on inventdata_history"
  ON inventdata_history FOR SELECT TO anon USING (true);

SELECT 'Backup tables created successfully' as status;
