-- ============================================
-- Boonyang Inventory Database Schema
-- Migration: init_schema
-- Created: 2025-03-15
-- ============================================

-- Enable required extension
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- ============================================
-- Table: botdata
-- Replaces BotData sheet (7 columns A-G)
-- ============================================
CREATE TABLE IF NOT EXISTS botdata (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Columns from Google Sheets
  item_code TEXT,
  field_unknown TEXT,
  item_name TEXT,
  lot_number TEXT,
  on_hand_quantity INTEGER DEFAULT 0,
  alternative_key_1 TEXT,
  alternative_key_2 TEXT,

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for search
CREATE INDEX IF NOT EXISTS idx_botdata_item_code ON botdata(item_code);
CREATE INDEX IF NOT EXISTS idx_botdata_item_name ON botdata(item_name);
CREATE INDEX IF NOT EXISTS idx_botdata_alt_key_1 ON botdata(alternative_key_1);
CREATE INDEX IF NOT EXISTS idx_botdata_alt_key_2 ON botdata(alternative_key_2);

-- ============================================
-- Table: inventdata
-- Replaces InventData sheet (2 columns A-B)
-- ============================================
CREATE TABLE IF NOT EXISTS inventdata (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Columns from Google Sheets
  item_name TEXT,
  stock_quantity INTEGER DEFAULT 0,

  -- Computed field for stock status
  stock_status TEXT GENERATED ALWAYS AS (
    CASE
      WHEN stock_quantity >= 4 THEN 'มีสินค้า'
      ELSE 'ติดต่อแอดมิน'
    END
  ) STORED,

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for search
CREATE INDEX IF NOT EXISTS idx_inventdata_item_name ON inventdata(item_name);
CREATE INDEX IF NOT EXISTS idx_inventdata_stock_status ON inventdata(stock_status);

-- Full-text search index for Thai/English
CREATE INDEX IF NOT EXISTS idx_inventdata_item_name_trgm ON inventdata USING GIN (item_name gin_trgm_ops);

-- ============================================
-- Table: userdata
-- Replaces UserData sheet (18 columns B-R, skip column A which is row number)
-- ============================================
CREATE TABLE IF NOT EXISTS userdata (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- LINE User Profile (Columns B-E)
  user_id TEXT,
  display_name TEXT,
  picture_url TEXT,
  status_message TEXT,

  -- Image & Registration Info (Columns F-H)
  image_formula TEXT,
  registration_date DATE,
  registration_time TIME(0),

  -- Language & Group Info (Columns I-K)
  language TEXT,
  group_name TEXT,
  group_id TEXT,

  -- Empty Column L (11) - Skipped
  -- Note: Column L (11) is empty in Google Sheets

  -- User Role & Status (Columns M-N)
  status_register TEXT,
  reference TEXT,

  -- Registration Data (Columns O-R)
  name TEXT,
  surname TEXT,
  shop_name TEXT,
  tax_id TEXT,

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  last_interaction_at TIMESTAMPTZ
);

-- Indexes for lookup
CREATE UNIQUE INDEX IF NOT EXISTS idx_userdata_user_id ON userdata(user_id);
CREATE INDEX IF NOT EXISTS idx_userdata_status_register ON userdata(status_register);
CREATE INDEX IF NOT EXISTS idx_userdata_shop_name ON userdata(shop_name);
CREATE INDEX IF NOT EXISTS idx_userdata_last_interaction ON userdata(last_interaction_at DESC);

-- ============================================
-- Table: system_settings
-- Replaces setting sheet
-- ============================================
CREATE TABLE IF NOT EXISTS system_settings (
  id SERIAL PRIMARY KEY,

  -- System switches
  bot_enabled BOOLEAN DEFAULT true,
  stock_enabled BOOLEAN DEFAULT true,
  stock_require_approval BOOLEAN DEFAULT true,
  register_required BOOLEAN DEFAULT true,

  -- LINE API tokens
  line_channel_token TEXT,

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default settings
INSERT INTO system_settings (bot_enabled, stock_enabled, stock_require_approval, register_required)
VALUES (true, true, true, true)
ON CONFLICT DO NOTHING;

-- ============================================
-- Table: reply_templates
-- Replaces reply sheet
-- ============================================
CREATE TABLE IF NOT EXISTS reply_templates (
  id SERIAL PRIMARY KEY,

  keyword TEXT NOT NULL UNIQUE,
  reply_type TEXT NOT NULL, -- 'text' | 'flex' | 'template'
  reply_content TEXT NOT NULL,

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- Enable Row Level Security (RLS)
-- ============================================
ALTER TABLE botdata ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventdata ENABLE ROW LEVEL SECURITY;
ALTER TABLE userdata ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE reply_templates ENABLE ROW LEVEL SECURITY;

-- Service role can do everything
DROP POLICY IF EXISTS "Service role: Full access to botdata" ON botdata;
CREATE POLICY "Service role: Full access to botdata"
  ON botdata FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Service role: Full access to inventdata" ON inventdata;
CREATE POLICY "Service role: Full access to inventdata"
  ON inventdata FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Service role: Full access to userdata" ON userdata;
CREATE POLICY "Service role: Full access to userdata"
  ON userdata FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Service role: Full access to system_settings" ON system_settings;
CREATE POLICY "Service role: Full access to system_settings"
  ON system_settings FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Service role: Full access to reply_templates" ON reply_templates;
CREATE POLICY "Service role: Full access to reply_templates"
  ON reply_templates FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Anon key (LINE Bot) can read
DROP POLICY IF EXISTS "Public read access on botdata" ON botdata;
CREATE POLICY "Public read access on botdata"
  ON botdata FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Public read access on inventdata" ON inventdata;
CREATE POLICY "Public read access on inventdata"
  ON inventdata FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Public read access on reply_templates" ON reply_templates;
CREATE POLICY "Public read access on reply_templates"
  ON reply_templates FOR SELECT TO anon USING (true);

-- ============================================
-- Functions & Triggers for auto-update updated_at
-- ============================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for each table
DROP TRIGGER IF EXISTS update_botdata_updated_at ON botdata;
CREATE TRIGGER update_botdata_updated_at
  BEFORE UPDATE ON botdata
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_inventdata_updated_at ON inventdata;
CREATE TRIGGER update_inventdata_updated_at
  BEFORE UPDATE ON inventdata
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_userdata_updated_at ON userdata;
CREATE TRIGGER update_userdata_updated_at
  BEFORE UPDATE ON userdata
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_system_settings_updated_at ON system_settings;
CREATE TRIGGER update_system_settings_updated_at
  BEFORE UPDATE ON system_settings
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_reply_templates_updated_at ON reply_templates;
CREATE TRIGGER update_reply_templates_updated_at
  BEFORE UPDATE ON reply_templates
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- Completed
-- ============================================
SELECT '✅ Database schema created successfully!' as status;
